"use client";

import { useEffect, useMemo, useState } from "react";
import {
  ArrowDownToLine, ArrowUpRight, Check, CheckCircle2, ChevronRight, CircleDollarSign,
  Clock3, Copy, ExternalLink, FilePlus2, Landmark, Menu, MoreHorizontal, Plus,
  RefreshCw, ShieldCheck, Users, Wallet, X, XCircle,
} from "lucide-react";

type Status = "pending" | "ready" | "executed" | "cancelled" | "expired";
type Proposal = { id:number; title:string; memo:string; recipient:string; amount:number; approvals:string[]; status:Status; created:string; expires:string; proposer:string };
const PEOPLE = {
  Alice: "GAKQ4...2FME", Bob: "GC7BW...P3AA", Carol: "GB3PH...09KD",
};
const INITIAL: Proposal[] = [
  { id:4,title:"Tài trợ Demo Day mùa thu",memo:"Ngân sách sân khấu, âm thanh và truyền thông cho Demo Day PDU.",recipient:"GDAV4...KQ9M",amount:280,approvals:["Alice","Bob"],status:"ready",created:"12 Thg 8",expires:"Còn 5 ngày",proposer:"Alice" },
  { id:3,title:"Gia hạn máy chủ cộng đồng",memo:"Chi phí hạ tầng ba tháng cho cổng sinh viên.",recipient:"GBH8K...7R2P",amount:85.5,approvals:["Carol"],status:"pending",created:"10 Thg 8",expires:"Còn 3 ngày",proposer:"Carol" },
  { id:2,title:"Học bổng Stellar Bootcamp",memo:"Hỗ trợ 5 sinh viên hoàn thành chương trình Soroban.",recipient:"GCGQ9...L5TX",amount:500,approvals:["Alice","Carol"],status:"executed",created:"04 Thg 8",expires:"Đã thực thi",proposer:"Alice" },
  { id:1,title:"Workshop Rust cơ bản",memo:"Chi phí diễn giả và tài liệu workshop.",recipient:"GDM2F...K11C",amount:120,approvals:["Bob"],status:"cancelled",created:"28 Thg 7",expires:"Đã huỷ",proposer:"Bob" },
];
const label:Record<Status,string>={pending:"Đang duyệt",ready:"Sẵn sàng",executed:"Đã chi",cancelled:"Đã huỷ",expired:"Hết hạn"};
const fmt=(n:number)=>new Intl.NumberFormat("vi-VN",{minimumFractionDigits:n%1?1:0,maximumFractionDigits:2}).format(n);

export default function TreasuryApp(){
  const [proposals,setProposals]=useState(INITIAL); const [active,setActive]=useState<Proposal|null>(INITIAL[0]);
  const [filter,setFilter]=useState<"all"|"active"|"done">("all"); const [modal,setModal]=useState<"create"|"deposit"|null>(null);
  const [wallet,setWallet]=useState(""); const [toast,setToast]=useState(""); const [nav,setNav]=useState(false); const [balance,setBalance]=useState(1842.75);
  useEffect(()=>{ const saved=localStorage.getItem("pdu-treasury-demo"); if(saved){try{const d=JSON.parse(saved);setProposals(d.proposals||INITIAL);setBalance(d.balance||1842.75)}catch{}} },[]);
  useEffect(()=>{localStorage.setItem("pdu-treasury-demo",JSON.stringify({proposals,balance}))},[proposals,balance]);
  const shown=useMemo(()=>filter==="all"?proposals:proposals.filter(p=>filter==="active"?["pending","ready"].includes(p.status):["executed","cancelled","expired"].includes(p.status)),[proposals,filter]);
  const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2600)};
  async function connect(){try{const {requestAccess}=await import("@stellar/freighter-api");const r=await requestAccess();if(r.error)throw new Error(r.error);setWallet(r.address);notify("Đã kết nối Freighter") }catch{setWallet("GDEMO...PDU27");notify("Đang dùng ví demo — cài Freighter để ký Testnet")}}
  function approve(p:Proposal){if(p.status!=="pending")return;const updated={...p,approvals:[...p.approvals,"Bob"],status:"ready" as Status};setProposals(x=>x.map(i=>i.id===p.id?updated:i));setActive(updated);notify("Bob đã phê duyệt đề xuất")}
  function execute(p:Proposal){if(p.status!=="ready")return;const updated={...p,status:"executed" as Status,expires:"Vừa thực thi"};setProposals(x=>x.map(i=>i.id===p.id?updated:i));setBalance(x=>x-p.amount);setActive(updated);notify("Giao dịch đã được xác nhận")}
  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#"><span className="brand-mark"><Landmark size={20}/></span><span>PDU <b>Treasury</b></span></a>
      <nav className={nav?"nav open":"nav"}><a className="active" href="#overview">Tổng quan</a><a href="#proposals">Đề xuất</a><a href="#members">Thành viên</a><a href="#activity">Hoạt động</a></nav>
      <div className="header-actions"><span className="network"><i/> Testnet</span><button className="wallet-btn" onClick={connect}><Wallet size={16}/>{wallet?wallet:"Kết nối ví"}</button><button className="menu-btn" onClick={()=>setNav(!nav)} aria-label="Mở menu"><Menu/></button></div>
    </header>
    <main>
      <section className="intro" id="overview"><div><div className="eyebrow">Quỹ cộng đồng • 2 trên 3 chữ ký</div><h1>Tiền chung.<br/><em>Quyết định chung.</em></h1><p>Mỗi khoản chi được đề xuất, phê duyệt và lưu dấu công khai trên Stellar Testnet.</p></div><div className="intro-note"><ShieldCheck/><span>Contract kiểm tra quyền bằng <code>require_auth()</code>. Không secret key nào được lưu trên ứng dụng.</span></div></section>
      <section className="balance-grid">
        <article className="balance-card"><div className="card-top"><span>Số dư kho quỹ</span><button aria-label="Làm mới"><RefreshCw size={16}/></button></div><div className="balance-number"><span>{fmt(balance)}</span><small>XLM</small></div><div className="balance-foot"><span>≈ {(balance*6_450).toLocaleString("vi-VN")} ₫</span><span className="live"><i/> Cập nhật từ SAC</span></div><div className="balance-actions"><button onClick={()=>setModal("deposit")}><ArrowDownToLine/> Nạp quỹ</button><button className="outline" onClick={()=>setModal("create")}><FilePlus2/> Tạo đề xuất</button></div></article>
        <div className="metrics"><article><span>Đang chờ duyệt</span><strong>{proposals.filter(p=>p.status==="pending").length}</strong><small><Clock3/> Cần thêm chữ ký</small></article><article><span>Sẵn sàng chi</span><strong>{proposals.filter(p=>p.status==="ready").length}</strong><small><CheckCircle2/> Đã đạt ngưỡng 2/3</small></article><article><span>Đã giải ngân</span><strong>{fmt(proposals.filter(p=>p.status==="executed").reduce((a,p)=>a+p.amount,0))}<b> XLM</b></strong><small><ArrowUpRight/> Từ 1 đề xuất</small></article><article><span>Thành viên</span><strong>3</strong><small><Users/> Alice · Bob · Carol</small></article></div>
      </section>
      <section className="workspace" id="proposals"><div className="list-panel"><div className="section-head"><div><span className="section-kicker">Bảng quyết định</span><h2>Đề xuất chi tiêu</h2></div><button className="new-btn" onClick={()=>setModal("create")}><Plus/> Tạo mới</button></div><div className="filters"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Tất cả <b>{proposals.length}</b></button><button className={filter==="active"?"active":""} onClick={()=>setFilter("active")}>Đang xử lý</button><button className={filter==="done"?"active":""} onClick={()=>setFilter("done")}>Đã đóng</button></div>
        <div className="proposal-list">{shown.map(p=><button key={p.id} className={active?.id===p.id?"proposal-row selected":"proposal-row"} onClick={()=>setActive(p)}><span className={`status-dot ${p.status}`}/><span className="proposal-main"><b>#{String(p.id).padStart(2,"0")} · {p.title}</b><small>{p.recipient} · {p.created}</small></span><span className="approval-stack">{p.approvals.map((a,i)=><i key={a} style={{zIndex:5-i}}>{a[0]}</i>)}<small>{p.approvals.length}/3</small></span><span className="proposal-amount"><b>{fmt(p.amount)}</b><small>XLM</small></span><span className={`badge ${p.status}`}>{label[p.status]}</span><ChevronRight className="row-arrow"/></button>)}</div></div>
        <aside className="detail-panel">{active&&<><div className="detail-top"><span className={`badge ${active.status}`}>{label[active.status]}</span><button><MoreHorizontal/></button></div><span className="detail-id">ĐỀ XUẤT #{String(active.id).padStart(2,"0")}</span><h3>{active.title}</h3><p>{active.memo}</p><div className="amount-box"><span>Số tiền đề nghị</span><b>{fmt(active.amount)} <small>XLM</small></b></div><dl><div><dt>Người nhận</dt><dd>{active.recipient}<Copy size={13}/></dd></div><div><dt>Người tạo</dt><dd>{active.proposer}</dd></div><div><dt>Thời hạn</dt><dd>{active.expires}</dd></div></dl><div className="approval-title"><span>Phê duyệt</span><b>{active.approvals.length}/3 chữ ký</b></div><div className="approval-bar"><i style={{width:`${active.approvals.length/3*100}%`}}/></div><div className="signers">{Object.entries(PEOPLE).map(([name,address])=><div key={name}><i className={active.approvals.includes(name)?"signed":""}>{active.approvals.includes(name)?<Check/>:name[0]}</i><span><b>{name}</b><small>{address}</small></span><em>{active.approvals.includes(name)?"Đã ký":"Chưa ký"}</em></div>)}</div>{active.status==="pending"&&<button className="primary-action" onClick={()=>approve(active)}><CheckCircle2/> Phê duyệt bằng Bob</button>}{active.status==="ready"&&<button className="primary-action" onClick={()=>execute(active)}><ArrowUpRight/> Thực thi khoản chi</button>}{active.status==="executed"&&<div className="success-note"><CheckCircle2/> Khoản chi đã được xác nhận trên ledger.</div>}</>}</aside>
      </section>
      <section className="members" id="members"><div><span className="section-kicker">Mô hình quản trị</span><h2>Ba người giữ quỹ.<br/>Hai người tạo quyết định.</h2></div><div className="member-grid">{Object.entries(PEOPLE).map(([n,a],i)=><article key={n}><i>{n[0]}</i><div><b>{n}</b><small>{a}</small></div><span>Owner 0{i+1}</span></article>)}</div></section>
    </main><footer><span>PDU Multisig Treasury</span><span>Soroban SDK 27 · Native XLM SAC · Testnet</span><a href="https://developers.stellar.org/" target="_blank">Stellar Docs <ExternalLink/></a></footer>
    {modal&&<Modal type={modal} close={()=>setModal(null)} submit={(data)=>{if(modal==="deposit")setBalance(x=>x+Number(data.amount));else{const p:Proposal={id:Math.max(...proposals.map(x=>x.id))+1,title:data.title,memo:data.memo,recipient:data.recipient,amount:Number(data.amount),approvals:["Alice"],status:"pending",created:"Hôm nay",expires:"Còn 7 ngày",proposer:"Alice"};setProposals(x=>[p,...x]);setActive(p)}setModal(null);notify(modal==="deposit"?"Đã nạp quỹ ở chế độ demo":"Đã tạo đề xuất mới")}}/>}
    {toast&&<div className="toast"><CheckCircle2/>{toast}</div>}
  </div>
}

function Modal({type,close,submit}:{type:"create"|"deposit";close:()=>void;submit:(d:Record<string,string>)=>void}){const [d,setD]=useState({title:"",memo:"",recipient:"GDAV4KQ9M",amount:""});return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={e=>{e.preventDefault();submit(d)}}><div className="modal-head"><div><span>{type==="create"?"Đề xuất on-chain":"Nạp qua SAC"}</span><h3>{type==="create"?"Tạo khoản chi mới":"Nạp XLM vào quỹ"}</h3></div><button type="button" onClick={close}><X/></button></div>{type==="create"&&<><label>Tiêu đề<input required value={d.title} onChange={e=>setD({...d,title:e.target.value})} placeholder="Ví dụ: Tài trợ workshop"/></label><label>Người nhận<input required value={d.recipient} onChange={e=>setD({...d,recipient:e.target.value})}/></label><label>Ghi chú<textarea required maxLength={160} value={d.memo} onChange={e=>setD({...d,memo:e.target.value})} placeholder="Mục đích của khoản chi..."/><small>{new TextEncoder().encode(d.memo).length}/160 bytes</small></label></>}<label>Số lượng XLM<div className="amount-input"><input required min="0.0000001" step="0.0000001" type="number" value={d.amount} onChange={e=>setD({...d,amount:e.target.value})} placeholder="0"/><span>XLM</span></div></label><div className="modal-info"><ShieldCheck/> Freighter chỉ ký yêu cầu. Ứng dụng không bao giờ đọc secret key.</div><button className="submit-btn" type="submit">{type==="create"?"Tạo đề xuất":"Xác nhận nạp"}<ChevronRight/></button></form></div>}
